
spring:
  datasource:
    name: test  #���ݿ���
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC #url
    username: root  #�û���
    password: 123456  #����
    driver-class-name: com.mysql.jdbc.Driver  #���ݿ���������

mybatis:
  mapper-locations: classpath:mapper/*.xml  #����ӳ���ļ�
  type-aliases-package: com.example.test.bean #����ʵ����